name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight
  workflow_dispatch: # Allows manual triggering

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      # Generate Snake Animation using the correct inputs
      - name: Generate Snake Animation
        uses: Platane/snk/svg-only@v2
        with:
          github_user_name: iabdamit # Your GitHub username
          outputs: dist/snake.svg

      - name: Commit and Push Snake Animation
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Updated Snake Animation ğŸ"
          file_pattern: dist/snake.svg
